runtime: go113
instance_class: F1
includes:
  - secret.yaml
handlers:
  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto
automatic_scaling:
    max_instances: 3
    min_instances: 0
    max_idle_instances: automatic
    min_pending_latency: 30ms
    max_pending_latency: automatic